CREATE DATABASE SISTEMA_TICKETS;
USE SISTEMA_TICKETS;

CREATE TABLE CATEGORIAS
(
	ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE NVARCHAR (50) NOT NULL,
    PRIMARY KEY (ID)
    
)ENGINE=INNODB;

CREATE TABLE PERSONAL
(
	ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE NVARCHAR(50) NOT NULL,
    APELLIDOS NVARCHAR(80) NOT NULL,
    TELEFONO NVARCHAR(10) NULL,
    DIRECCION NVARCHAR(150) NULL,
	PRIMARY KEY(ID)
    
)ENGINE=INNODB;

CREATE TABLE TICKETS
(
	ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE NVARCHAR(50) NOT NULL,
    DESCRIPCION NVARCHAR(100) NULL,
    PRIORIDAD NVARCHAR(1) NOT NULL,
    PERSONALID INT NOT NULL,
    CATEGORIAID INT NOT NULL,
    ESTATUS NVARCHAR(3) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (PERSONALID)	REFERENCES PERSONAL(ID)	ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (CATEGORIAID) REFERENCES CATEGORIAS(ID) ON UPDATE CASCADE ON DELETE RESTRICT
    
)ENGINE=INNODB;



INSERT INTO PERSONAL (NOMBRE,APELLIDOS,TELEFONO,DIRECCION) VALUES ("JOSUE","GAMEZ CARRASCO","1234567890","ALVARO OBREGON #115");
INSERT INTO CATEGORIAS (NOMBRE) VALUES ("INCIDENCIA");
INSERT INTO TICKETS (NOMBRE, DESCRIPCION, PRIORIDAD, PERSONALID, CATEGORIAID,ESTATUS) VALUES("BAJA DE MATERIA","QUISIERA DAR DE BAJA LA MATERIA DE GRAFICACION.","1","1","1","ESP");

CREATE VIEW VISTA_TICKETS AS
SELECT TICKETS.ID, TICKETS.NOMBRE,DESCRIPCION,PRIORIDAD,PERSONAL.NOMBRE PERSONAL,CATEGORIAS.NOMBRE CATEGORIAS, ESTATUS from TICKETS
INNER JOIN PERSONAL ON  PERSONAL.ID = TICKETS.PERSONALID
INNER JOIN CATEGORIAS ON  CATEGORIAS.ID = TICKETS.CATEGORIAID;
