CREATE DATABASE SISTEMA_TICKETS;
USE SISTEMA_TICKETS;

CREATE TABLE CATEGORIAS
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE NVARCHAR (50) NOT NULL
    
)ENGINE=INNODB;

CREATE TABLE PERSONAL
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE NVARCHAR(50) NOT NULL,
    APELLIDOS NVARCHAR(80) NOT NULL,
    TELEFONO NVARCHAR(10) NULL,
    DIRECION NVARCHAR(150) NULL
    
)ENGINE=INNODB;

CREATE TABLE TICKETS
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE NVARCHAR(50) NOT NULL,
    DESCRIPCION NVARCHAR(100) NULL,
    PRIORIDAD NVARCHAR(100) NOT NULL,
    PERSONALID INT NOT NULL,
    CATEGORIAID INT NOT NULL,
    ESTATUS NVARCHAR(3) NOT NULL,
    FOREIGN KEY (PERSONALID)	REFERENCES PERSONAL(ID)	ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (CATEGORIAID) REFERENCES CATEGORIAS(ID) ON UPDATE CASCADE ON DELETE RESTRICT
    
)ENGINE=INNODB;